!!python/object/apply:collections.OrderedDict
- - [DESCRIPTION, 'Each metric is reported with two values: The first value is the
      value of the metric, and the second value is the difference in the metric relative
      to a reference training summary, if provided']
  - - SYSTEM_CLASS
    - accuracy: 0.6757679180887372
      all_labels: [diffuse, diffuse__diffuse, diffuse__diffuse__disordered, unidentified,
        diffuse__disordered]
      confusion_matrix:
      - ['diffuse                      ', '[[ 19  43   1   8   2]']
      - ['diffuse__diffuse             ', ' [  2 127  18   0   0]']
      - ['diffuse__diffuse__disordered ', ' [  0  12  14   0   3]']
      - ['unidentified                 ', ' [  3   0   0  34   0]']
      - ['diffuse__disordered          ', ' [  0   2   1   0   4]]']
      f1: 0.5928656233286754
      precision: 0.6295234035643242
      recall: 0.6194651323742355
  - - CLASSIFIERS
    - diffuse:
        noise_model:
          model_type: logistic_regressor
          scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop0:
          form:
            model_type: logistic_regressor
            scores: {accuracy: 1.0, f1: 1.0, precision: 1.0, recall: 1.0}
          guinier_porod:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
          spherical:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
      diffuse__diffuse:
        noise_model:
          model_type: logistic_regressor
          scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop0:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          guinier_porod:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop1:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          spherical:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
      diffuse__diffuse__disordered:
        noise_model:
          model_type: logistic_regressor
          scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop0:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          guinier_porod:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop1:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          spherical:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop2:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          interaction:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          spherical:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
      diffuse__disordered:
        noise_model:
          model_type: logistic_regressor
          scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop0:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          guinier_porod:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
          spherical:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
        pop1:
          form:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          guinier_porod:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
          interaction:
            model_type: logistic_regressor
            scores: {accuracy: null, f1: null, precision: null, recall: null}
          spherical:
            distribution:
              model_type: logistic_regressor
              scores: {accuracy: null, f1: null, precision: null, recall: null}
      main_classifiers:
        crystalline_binary:
          model_type: logistic_regressor
          scores: {accuracy: null, f1: null, precision: null, recall: null}
        diffuse:
          model_type: non_linear_svm
          scores: {accuracy: 0.7818181818181819, f1: 0.6936999651931779, precision: 0.845098393211771,
            recall: 0.6781287857608796}
        diffuse__disordered:
          model_type: logistic_regressor
          scores: {accuracy: 0.7777777777777778, f1: 0.6785714285714286, precision: 0.6666666666666666,
            recall: 0.6995073891625616}
        diffuse_binary:
          model_type: knn
          scores: {accuracy: 0.962457337883959, f1: 0.9783037475345168, precision: 0.9880478087649402,
            recall: 0.96875}
        disordered_binary:
          model_type: random_forest
          scores: {accuracy: 0.8805460750853242, f1: 0.5569620253164557, precision: 0.5116279069767442,
            recall: 0.6111111111111112}
  - - REGRESSORS
    - diffuse:
        noise:
          flat:
            I0_fraction:
              model_type: ridge_regressor
              scores: {MAE: 0.37248220524863895, coef_of_determination: -0.01747538296525253}
        pop0:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: 0.3724822052486388, coef_of_determination: -0.017475382965252306}
          guinier_porod:
            D:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
            distribution:
              single: {}
            rg:
              model_type: ridge_regressor
              scores: {MAE: 0.23136312687826813, coef_of_determination: 0.8994351586246239}
          spherical:
            distribution:
              r_normal:
                sigma:
                  model_type: ridge_regressor
                  scores: {MAE: 0.5565605385463399, coef_of_determination: 0.41259653213534675}
            r:
              model_type: ridge_regressor
              scores: {MAE: 0.23975526014869186, coef_of_determination: 0.8827530504538623}
      diffuse__diffuse:
        noise:
          flat:
            I0_fraction:
              model_type: ridge_regressor
              scores: {MAE: 0.2872849485002573, coef_of_determination: -0.029342580516502625}
        pop0:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: 0.17093468044442237, coef_of_determination: 0.825005679992765}
          guinier_porod:
            D:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
            distribution:
              single: {}
            rg:
              model_type: ridge_regressor
              scores: {MAE: 0.7426000591462236, coef_of_determination: 0.10467038394434303}
        pop1:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: 0.16634776183609404, coef_of_determination: 0.8623355070247728}
          spherical:
            distribution:
              r_normal:
                sigma:
                  model_type: ridge_regressor
                  scores: {MAE: 0.40631403592241316, coef_of_determination: 0.5642350973283287}
            r:
              model_type: ridge_regressor
              scores: {MAE: 0.2698842776525572, coef_of_determination: 0.8149142178393514}
      diffuse__diffuse__disordered:
        noise:
          flat:
            I0_fraction:
              model_type: ridge_regressor
              scores: {MAE: 0.5167552632475625, coef_of_determination: 0.5361884775445052}
        pop0:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: 0.39142600072181943, coef_of_determination: 0.6277278618924116}
          guinier_porod:
            D:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
            distribution:
              single: {}
            rg:
              model_type: ridge_regressor
              scores: {MAE: 0.640886167283464, coef_of_determination: 0.27597442546139483}
        pop1:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: 0.46759831302887106, coef_of_determination: 0.6573640943098097}
          spherical:
            distribution:
              r_normal:
                sigma:
                  model_type: ridge_regressor
                  scores: {MAE: 0.6820798600323722, coef_of_determination: 0.384924425065012}
            r:
              model_type: ridge_regressor
              scores: {MAE: 0.5775697628061531, coef_of_determination: 0.3583694692989049}
        pop2:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: 0.467366273726871, coef_of_determination: 0.6567518408722715}
          interaction:
            hard_spheres:
              r_hard:
                model_type: ridge_regressor
                scores: {MAE: 0.6059149007004284, coef_of_determination: 0.38936441278516654}
              v_fraction:
                model_type: ridge_regressor
                scores: {MAE: 0.6560108597513271, coef_of_determination: -0.10457738990601473}
          spherical:
            distribution:
              r_normal:
                sigma:
                  model_type: ridge_regressor
                  scores: {MAE: 0.6731396904192931, coef_of_determination: -0.01872078265581245}
              single: {}
            r:
              model_type: ridge_regressor
              scores: {MAE: 0.7668988775358384, coef_of_determination: 0.04229840353155101}
      diffuse__disordered:
        noise:
          flat:
            I0_fraction:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
        pop0:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: null, coef_of_determination: null}
          guinier_porod:
            D:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
            distribution:
              single: {}
            rg:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
          spherical:
            distribution:
              r_normal:
                sigma:
                  model_type: ridge_regressor
                  scores: {MAE: null, coef_of_determination: null}
            r:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
        pop1:
          I0_fraction:
            model_type: ridge_regressor
            scores: {MAE: null, coef_of_determination: null}
          guinier_porod:
            D:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
            distribution:
              single: {}
            rg:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
          interaction:
            hard_spheres:
              r_hard:
                model_type: ridge_regressor
                scores: {MAE: null, coef_of_determination: null}
              v_fraction:
                model_type: ridge_regressor
                scores: {MAE: null, coef_of_determination: null}
          spherical:
            distribution:
              r_normal:
                sigma:
                  model_type: ridge_regressor
                  scores: {MAE: null, coef_of_determination: null}
            r:
              model_type: ridge_regressor
              scores: {MAE: null, coef_of_determination: null}
